# Generated by Django 5.0.6 on 2024-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0002_userblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogs',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
